M48
; DRILL file {KiCad 7.0.9-7.0.9~ubuntu22.04.1} date Tue 12 Dec 2023 09:19:18 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-12T21:19:18-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9-7.0.9~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X14.03Y58.425
X14.03Y53.575
T2
X11.0Y58.725
X11.0Y53.275
T0
M30
